cartolinha/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rounds
  resources :teams
  resources :games
  resources :players
  resources :categories
  resources :actions

  #match 'confrontos' =>'games#confrontos', via:'get'
  get "confrontos/:id", to: "games#confrontos", as: "confrontos_rodada"

    get "avaliar/:id", to: "actions#avaliar_jogadores", as: "avaliar_jogadores"

  #match 'confrontos/:id' =>'games#mostrarConfrontos', via:'get'
end

cartolinha/app/models/action.rb
class Action < ApplicationRecord
	belongs_to :category
	belongs_to :player
end

cartolinha/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cartolinha/app/models/category.rb
class Category < ApplicationRecord
	has_many :actions
end

cartolinha/app/models/dispute.rb
class Dispute < ApplicationRecord
end

cartolinha/app/models/game.rb
class Game < ApplicationRecord
	belongs_to :round
	belongs_to :team_home, class_name: "Team", foreign_key: "team_home_id"
	belongs_to :team_away, class_name: "Team", foreign_key: "team_away_id"
	
end
=begin
class Produto < ApplicationRecord
	has_and_belongs_to_many :pedidos,  :join_table => :items
end


class Pedido < ApplicationRecord
	has_and_belongs_to_many :produtos,  :join_table => :items
end

empresa
has_many contratacoes
has_many :funcionarios, through: :contratacoes

funcionario
has_many contratacoes
contratação
belongs_to :funcionario
belongs_to :empresa

empresa.id 

contratacoes = Contratacao.where("empresa_id = ?", @empresa.id)
@empresa.contratacoes
=end

cartolinha/app/models/player.rb
class Player < ApplicationRecord
	belongs_to :team
	has_many :actions

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>"}, default_url: "/system/teams/:style/missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

cartolinha/app/models/round.rb
class Round < ApplicationRecord
	has_many :games
end

cartolinha/app/models/team.rb
class Team < ApplicationRecord
	has_many :players
    has_many :games
  has_attached_file :escudo, styles: { medium: "300x300>", thumb: "30x30>"}, default_url: "/system/teams/:style/missing.jpg"
  validates_attachment_content_type :escudo, content_type: /\Aimage\/.*\z/
end

cartolinha/app/controllers/actions_controller.rb
class ActionsController < ApplicationController
	def new
		puts "hahaha"
	end

	def avaliar_jogadores
		@games = Game.joins("inner join Teams on Teams.id = Games.team_home_id or Teams.id = Games.team_away_id
		inner join Players on Players.team_id = Teams.id").where({id: params[:id]}).group('team_home_id', 'id')

		puts "rfkrkfp"
		puts @games[0].team_home.nome
		puts @games[0].team_home.players[1].nome
		puts "xxx"
	end
end

cartolinha/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
def index
		@categories = Category.order :id
	end

	def show
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		@category.save
		
		redirect_to(action: "show", id: @category)
    end

    def edit
		@category = Category.find (params[:id])
	end

	def update
		@category = Category.find(params[:id])
		@category.update_attributes(category_params)

		redirect_to(action: "show", id: @category)
	end	

	def destroy
		@category = Category.find(params[:id])
		@category.destroy

		redirect_to(action: "index")
	end

	def category_params
		params.require(:category).permit(:nome, :descricao, :pontuacao)
	end
end

cartolinha/app/controllers/disputes_controller.rb
class DisputesController < ApplicationController
 def receiveObject(disputeHome, disputeAway)
 	@disputeHome = Dispute.new 
 	@disputeHome.game_id = disputeHome.game_id
 	@disputeHome.team_id = disputeHome.team_id
 	@disputeHome.home_team = disputeHome.home_team
    @disputeHome.save
puts "Save 1"
    @disputeAway = Dispute.new
 	@disputeAway.game_id = disputeAway.game_id
 	@disputeAway.team_id = disputeAway.team_id
 	@disputeAway.home_team = disputeAway.home_team
 	@disputeAway.save
 	puts "Save 2"
 end	

 def dispute_params
	params.require(:dispute).permit(:game_id, :team_id, :home_team)
 end
end

cartolinha/app/controllers/games_controller.rb
class GamesController < ApplicationController

	before_action :preparar_form, only: [:new, :create, :edit, :update]

	def index
		@games = Game.order :id
	end

	def show
		@game = Game.find(params[:id])
	end

	def new
		@game = Game.new
	end

	def create
		@game = Game.new(game_params)
		@game.save
		puts @game.estadio
		puts 11111111111111111111111111111111111111111111
		puts @game.errors.inspect
		redirect_to @game
	end
    
    def edit
		@game = Game.find(params[:id])
	end

	def update
       @game = Game.find(params[:id])
       puts "eçfpr"
       puts @game.estadio
       puts @game.errors.inspect
       @game.update_attributes(game_params)

		redirect_to(action: "show", id: @game)   
    end

    def destroy
		@game = Game.find(params[:id])
		@game.destroy

		redirect_to(action: "index")
	end

    def confrontos
    	@games =Game.where({round_id: params[:id]})
    end
    
	private

	def game_params
		params.require(:game).permit(:dataJogo, :estadio, :cidade, :horario, :round_id, :team_home_id, :team_away_id)
	end

	def preparar_form
		@teams =  Team.order :nome
		@rounds = Round.order :nome
	end
end

cartolinha/app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def index
		@players = Player.order :id
	end

	def show
		@player = Player.find(params[:id])
	end

	def new
		preparar_form
		@player = Player.new
	end

	def create
		@player = Player.new(player_params)
		puts @player.nome
		@player.save
		redirect_to(action: "show", id: @player)
    end

    def edit
    	preparar_form
		@player = Player.find (params[:id])
	end

	def update
		@player = Player.find(params[:id])
		@player.update_attributes(player_params)

		redirect_to(action: "show", id: @player)
	end	

	def destroy
		@player = Player.find(params[:id])
		@player.destroy

		redirect_to(action: "index")
	end

	def player_params
		params.require(:player).permit(:nome, :dataNascimento, :avatar, :team_id)
	end

	def preparar_form
		@teams =  Team.order :nome
	end
end

cartolinha/app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
	def index
		@rounds = Round.order :id
	end

	def show
		@round = Round.find(params[:id])
	end

	def destroy
		@round = Round.find(params[:id])
		@round.destroy

		redirect_to(action: "index")
	end

	def new
		@round = Round.new
	end

	def create
		#nome = params[:nome]
		@round = Round.new(round_params)
		@round.save
		redirect_to(action: "show", id: @round)
	end

	def edit
		@round = Round.find(params[:id])
	end

	def update
		@round = Round.find(params[:id])
		@round.update_attributes(round_params)

		redirect_to(action: "show", id: @round)
	end	

	def round_params
		params.require(:round).permit(:nome)
	end
end

cartolinha/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	def index
		@teams = Team.order :id
	end

	def show
		@team = Team.find(params[:id])
	end

	def new
		@team = Team.new
	end

	def create
		@team = Team.new(team_params)
		@team.escudo = params[:team][:escudo] 
		@team.save
		redirect_to(action: "show", id: @team)
	end

	def edit
		@team = Team.find(params[:id])
	end

	def update
		@team = Team.find(params[:id])
		@team.update_attributes(team_params)

		redirect_to(action: "show", id: @team)
	end	

	def destroy
		@team = Team.find(params[:id])
		@team.destroy

		redirect_to(action: "index")
	end

	def team_params
		params.require(:team).permit(:nome, :escudo)
	end
end

cartolinha/app/helpers/actions_helper.rb
module ActionsHelper
end

cartolinha/app/helpers/application_helper.rb
module ApplicationHelper
end

cartolinha/app/helpers/categories_helper.rb
module CategoriesHelper
end

cartolinha/app/helpers/disputes_helper.rb
module DisputesHelper
end

cartolinha/app/helpers/games_helper.rb
module GamesHelper
end

cartolinha/app/helpers/players_helper.rb
module PlayersHelper
end

cartolinha/app/helpers/rounds_helper.rb
module RoundsHelper
end

cartolinha/app/helpers/team_helper.rb
module TeamHelper
end

cartolinha/app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
<table class="table table-bordered">
	<tbody>
    <tr>
      <th scope="row">
      	<td>Nome:</td>
      	<td><%= f.text_field :nome %></td>
      	</th>
    </tr>
    <tr>
      <th scope="row">
      	<td>Descrição:</td> 
      	<td><%= f.text_area :descricao, cols: 40, rows: 10%></td>
      </th>
    </tr>
    <tr>
      <th scope="row">
      	<td>Pontuação:</td>
      	<td><%= f.text_field :pontuacao %></td>
      </th>
    </tr>
</tbody>
</table>
<%= f.submit %>
<% end %>

cartolinha/app/views/categories/edit.html.erb
<h1> Edição de Rodada </h1>
<%= render partial: "form" %>

cartolinha/app/views/categories/index.html.erb
<% contador = 1 %>
<div align="center"><h1> Categorias de Avaliação </h1></div></br>
<%= link_to 'Novo' , {action: 'new'} , class: "btn btn-primary btn-sm"  %>
<table class="table table-hover">
<thead>
	<tr>	
		<th scope="col">
			<td>#</td>
		    <td>Nome</td>
		    <td>Pontuação</td>
		    <td>Mostrar</td>
		    <td>Editar</td>
		    <td>Excluir</td>
		</th>
    </tr>
</thead>
<tbody>
	<% @categories.each do |category| %>
	<tr>
	<th scope="row">
		<td><%=contador %></td>
		<td><%=category.nome %></td>
		<td><%=category.pontuacao %></td>
		<td><%= link_to 'Mostrar' , {action: 'show', id: category} , class: "btn btn-primary btn-sm"  %></td>
		<td><%= link_to 'Editar' , {action: 'edit', id: category} , class: "btn btn-secondary btn-sm"  %></td>
		<td><%= link_to 'Deletar' , {action: 'destroy', id: category} , {method: "delete", data: { confirm: "Deseja realmente excluir?" },class: "btn btn-danger btn-sm"}  %></td>
	</th>
    </tr>
    <% contador += 1 %>
	<%  end %>
</tbody>
</table>

cartolinha/app/views/categories/new.html.erb
<h1> Edição de Rodada </h1>
<%= render partial: "form" %>

cartolinha/app/views/categories/show.html.erb
<h1>Dados da Rodada</h1>
<p>
	<b>Nome:</b>
	<%= @category.nome %><br/>
	<b>Descrição:</b>
	<%= @category.descricao %><br/>
	<b>Pontuação:</b>
	<%= @category.pontuacao %><br/>
</p>
<td><%= link_to 'Voltar' , {action: 'index'}, class: "btn btn-primary" %></td>

cartolinha/app/views/games/_form.html.erb
<%= form_with model: @game do |f| %>
<table>
	<tr>
		<td>Estádio:</td>
		<td><%= f.text_field :estadio %> </td>
	</tr>
	<tr>
		<td>Cidade:</td>
		<td><%= f.text_field :cidade %></td>
	</tr>
	<tr>
		<td>Horário:</td>
		<td><%= f.text_field :horario %></td>
	</tr>
	<tr>
	    <td>Rodada:</td>
	    <td><%= f.collection_select(:round_id, @rounds, :id, :nome, :prompt => true)  %> </td>
	<tr>
	<tr>
	    <td>Mandante:</td>
	    <td><%= f.collection_select(:team_home_id, @teams, :id, :nome, :prompt => true)  %> </td>
	<tr>
	<tr>
	    <td>Visitante:</td>
	    <td><%= f.collection_select(:team_away_id, @teams, :id, :nome, :prompt => true)  %></td> 
	<tr>
	<tr><td><%= f.submit %></td></tr>
<% end %>

cartolinha/app/views/games/confrontos.html.erb
Entrou Aqui
<p>
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Link with href
  </a>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Button with data-target
  </button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
  </div>
</div>
<% contador = 1 %>
<div align="center" ><h1>Confrontos <%= @games[0].round.nome%> </h1></div></br>
<table class="table table-hover" align="center"  width="100" height="50">
<tbody>
	<% @games.each do |game| %>
	<tr valign="middle">
	<th scope="row">
		<td width =30% ><font size="2"><%=game.estadio %><br/><%=game.dataJogo.strftime("%m/%d/%Y") %> - <%=game.horario %></font></td>
		<td width =30% valign="middle"><b><%= game.team_home.nome %></b> <%= image_tag game.team_home.escudo.url(:thumb) %> X <%=image_tag game.team_away.escudo.url(:thumb) %> <b><%= game.team_away.nome %></b> </td>
		<td><%= link_to 'Avaliar' , avaliar_jogadores_path(game) , class: "btn btn-primary btn-sm"  %></td>
	</th>
    </tr>
    <hr/>
    <% contador += 1 %>
	<%  end %>
</tbody>
</table>

cartolinha/app/views/games/edit.html.erb
<h1> Edição de Confronto </h1>
<%= render partial: "form" %>

cartolinha/app/views/games/index.html.erb
<% contador = 1 %>
<div align="center"><h1> Jogo </h1></div></br>
<%= link_to 'Novo' , {action: 'new'} , class: "btn btn-primary btn-sm"  %>

<table class="table table-hover">
<thead>
	<tr>	
		<th scope="col">
			<td>#</td>
		    <td>Nome</td>
		    <td>Escudo</td>
		    <td>Rodada</td>
		    <td>Mostrar</td>
		    <td>Editar</td>
		    <td>Excluir</td>
		</th>
    </tr>
</thead>
<tbody>
	<% @games.each do |game| %>
	<tr>
	<th scope="row">
		<td><%=contador %></td>
		<td><%=game.estadio %></td>
		<td><%= game.cidade %></td>
		<td><%= game.round.nome %></td>
		<td><%= link_to 'dd' , confrontos_rodada_path(game.round_id) , class: "btn btn-primary btn-sm"  %></td>
		<td><%= link_to 'Mostrar' , {action: 'show', id: game} , class: "btn btn-primary btn-sm"  %></td>
		<td><%= link_to 'Editar' , {action: 'edit', id: game} , class: "btn btn-secondary btn-sm"  %></td>
		<td><%= link_to 'Deletar' , {action: 'destroy', id: game} , {method: "delete", data: { confirm: "Deseja realmente excluir?" },class: "btn btn-danger btn-sm"}  %></td>
	</th>
    </tr>
    <% contador += 1 %>
	<%  end %>
</tbody>
</table>

cartolinha/app/views/games/new.html.erb
<h1> Cadastro de Confronto </h1>
<%= render partial: "form" %>

cartolinha/app/views/games/show.html.erb
<h1>Dados do Time</h1>
<p>
	<b>Estádio:</b>
	<%= @game.estadio %>
</p>
<p>
	<b>Cidade:</b>
	<%= @game.cidade %>
</p>
<p>
	<b>Horário:</b>
	<%= @game.horario %>
</p>
<p>
<td><%= link_to 'Voltar' , {action: 'index'}, class: "btn btn-primary" %></td>

cartolinha/app/views/players/_form.html.erb
<%= form_with model: @player, html: { multipart: true } do |f| %>
<table>
	<tr>
		<td><%= f.label :nome %></td>
		<td><%= f.text_field :nome %> </td>
	</tr>
		<tr>
		<td>Data de Nascimento</td>
		<td><%= f.text_field :dataNascimento %> </td>
	</tr>
		<tr>
	    <td><%= f.label :time %></td>
	    <td><%= f.collection_select(:team_id, @teams, :id, :nome, :prompt => true)  %> </td>
	</tr>
	<tr>
		<td><%= f.label :avatar %></td>
		<td><%= f.file_field :avatar %></td>
	</tr>
	<tr>
	<tr><td><%= f.submit "Confirmar", class:  'btn btn-secondary btn-sm' %></td></tr>
<% end %>

cartolinha/app/views/players/edit.html.erb
<h1> Cadastro de Confronto </h1>
<%= render partial: "form" %>

cartolinha/app/views/players/index.html.erb
<% contador = 1 %>
<div align="center"><h1> Jogadores </h1></div></br>
<%= link_to 'Novo' , {action: 'new'} , class: "btn btn-primary btn-sm"  %>
<table class="table table-hover">
<thead>
	<tr>	
		<th scope="col">
			<td>#</td>
		    <td></td>
		    <td>Nome</td>
		    <td>Time</td>
		    <td>Mostrar</td>
		    <td>Editar</td>
		    <td>Excluir</td>
		</th>
    </tr>
</thead>
<tbody>
	<% @players.each do |player| %>
	<tr>
	<th scope="row">
		<td><%=contador %></td>
		<td><%= image_tag player.avatar.url(:thumb) %></td>
		<td><%=player.nome %></td>
		<td><%= image_tag player.team.escudo.url(:thumb) %></td>
		<td><%= link_to 'Mostrar' , {action: 'show', id: player} , class: "btn btn-primary btn-sm"  %></td>
		<td><%= link_to 'Editar' , {action: 'edit', id: player} , class: "btn btn-secondary btn-sm"  %></td>
		<td><%= link_to 'Deletar' , {action: 'destroy', id: player} , {method: "delete", data: { confirm: "Deseja realmente excluir?" },class: "btn btn-danger btn-sm"}  %></td>
	</th>
    </tr>
    <% contador += 1 %>
	<%  end %>
</tbody>
</table>

cartolinha/app/views/players/new.html.erb
<% contador = 1 %>
<div align="center"><h1> Jogadores </h1></div></br>
<%= link_to 'Novo' , {action: 'new'} , class: "btn btn-primary btn-sm"  %>
<table class="table table-hover">
<thead>
	<tr>	
		<th scope="col">
			<td>#</td>
		    <td>Nome</td>
		    <td>Escudo</td>
		    <td>Mostrar</td>
		    <td>Editar</td>
		    <td>Excluir</td>
		</th>
    </tr>
</thead>
<tbody>
	<% @teams.each do |team| %>
	<tr>
	<th scope="row">
		<td><%=contador %></td>
		<td><%=team.nome %></td>
		<td><%= image_tag team.escudo.url(:thumb) %></td>
		<td><%= link_to 'Mostrar' , {action: 'show', id: team} , class: "btn btn-primary btn-sm"  %></td>
		<td><%= link_to 'Editar' , {action: 'edit', id: team} , class: "btn btn-secondary btn-sm"  %></td>
		<td><%= link_to 'Deletar' , {action: 'destroy', id: team} , {method: "delete", data: { confirm: "Deseja realmente excluir?" },class: "btn btn-danger btn-sm"}  %></td>
	</th>
    </tr>
    <% contador += 1 %>
	<%  end %>
</tbody>
</table>

cartolinha/app/views/players/show.html.erb
<h1>Perfil do Jogador</h1>
<p>
	<b></b>
	<%= image_tag @player.avatar.url(:medium) %>
</p>
<p>
	<b>Nome:</b>
	<%= @player.nome %>
</p>
<p>
	<b>Data de Nascimento:</b>
	<%= @player.dataNascimento %>
</p>
<p>
	<b>Time:</b>
	<%= image_tag @player.team.escudo.url(:thumb) %> - <%= @player.team.nome%>
</p>
<p>
<td><%= link_to 'Voltar' , {action: 'index'}, class: "btn btn-primary" %></td>

cartolinha/app/views/rounds/_form.html.erb
<%= form_for @round do |f| %>
		Nome: <%= f.text_field :nome %> <br/>
<%= f.submit %>
<% end %>

cartolinha/app/views/rounds/index.html.erb
<% contador = 1 %>
<div align="center"><h1> Rodadas do Brasileirão </h1></div></br>
<%= link_to 'Novo' , new_round_path , class: "btn btn-primary btn-sm"  %>
<table class="table table-hover">
<thead>
	<tr>	
		<th scope="col">
			<td>#</td>
		    <td>Nome</td>
		    <td>Mostrar</td>
		    <td>Editar</td>
		    <td>Excluir</td>
		</th>
    </tr>
</thead>
<tbody>
	<% @rounds.each do |round| %>
	<tr>
	<th scope="row">
		<td><%=contador %></td>
		<td><%=round.nome %></td>
		<td><%= link_to 'Confrontos' , confrontos_rodada_path(round) , class: "btn btn-primary btn-sm"  %></td>
		<td><%= link_to 'Mostrar' , round_path(round) , class: "btn btn-primary btn-sm"  %></td>
		<td><%= link_to 'Editar' , edit_round_path(round) , class: "btn btn-secondary btn-sm"  %></td>
		<td><%= link_to 'Deletar' , round_path(round) , {method: "delete", data: { confirm: "Deseja realmente excluir?" },class: "btn btn-danger btn-sm"}  %></td>
	</th>
    </tr>
    <% contador += 1 %>
	<%  end %>
</tbody>
</table>

cartolinha/app/views/rounds/new.html.erb
<h1> Cadastro de Rodada </h1>
<%= render partial: "form" %>

cartolinha/app/views/rounds/show.html.erb
<h1>Dados da Rodada</h1>
<p>
	<b>Nome:</b>
	<%= @round.nome %>
</p>
<td><%= link_to 'Voltar' , {action: 'index'}, class: "btn btn-primary" %></td>